spring:
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: user
        password: passwd
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        open-in-view: true
        properties:
            hibernate:
                search:
                    default: #
#logging:
#    level:
#        org.hibernate.SQL: DEBUG
#        org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
#        org.springframework: DEBUG
